[package]
name = "node-template-release"
version = "3.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0 WITH Classpath-exception-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { features = ["derive"], workspace = true }
flate2 = { workspace = true }
fs_extra = { workspace = true }
glob = { workspace = true }
itertools = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
toml_edit = { workspace = true }

