[package]
name = "substrate-rpc-client"
version = "0.33.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Shared JSON-RPC client"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true }
jsonrpsee = { features = ["ws-client"], workspace = true }
log = { workspace = true, default-features = true }
sc-rpc-api = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

[dev-dependencies]
sp-core = { workspace = true, default-features = true }
tokio = { features = ["macros", "rt-multi-thread", "sync"], workspace = true, default-features = true }

