[package]
name = "pallet-staking-runtime-api"
version = "14.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "RPC runtime API for transaction payment FRAME pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
sp-api = { workspace = true }
sp-staking = { workspace = true }

[features]
default = ["std"]
std = ["codec/std", "sp-api/std", "sp-staking/std"]

