[package]
name = "pallet-revive-uapi"
version = "0.1.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Exposes all the host functions that a contract can import."

[lints]
workspace = true

[dependencies]
bitflags = { workspace = true }
codec = { features = [
	"derive",
	"max-encoded-len",
], optional = true, workspace = true }
pallet-revive-proc-macro = { workspace = true }
paste = { workspace = true }
scale-info = { features = ["derive"], optional = true, workspace = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
polkavm-derive = { version = "0.19.0" }

[package.metadata.docs.rs]
features = ["unstable-hostfn"]
targets = ["riscv64imac-unknown-none-elf"]

[features]
default = ["scale"]
scale = ["dep:codec", "scale-info"]
unstable-hostfn = []

