[package]
name = "test-parachains"
description = "Integration tests using the test-parachains"
version = "1.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
tiny-keccak = { features = ["keccak"], workspace = true }

test-parachain-adder = { workspace = true }
test-parachain-halt = { workspace = true }

[dev-dependencies]
sp-core = { workspace = true, default-features = true }

[features]
default = ["std"]
std = ["codec/std", "test-parachain-adder/std", "test-parachain-halt/std"]

