[package]
name = "zombienet-backchannel"
description = "Zombienet backchannel to notify test runner and coordinate with malus actors."
readme = "README.md"
publish = false
version = "1.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true, default-features = true }
futures-util = { workspace = true, default-features = true }
gum = { workspace = true, default-features = true }
reqwest = { features = ["rustls-tls"], workspace = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }
tokio = { features = ["macros", "net", "rt-multi-thread", "sync"], workspace = true }
tokio-tungstenite = { workspace = true }
url = { workspace = true }

