[package]
name = "substrate-cli-test-utils"
description = "CLI testing utilities"
version = "0.1.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
assert_cmd = { workspace = true }
futures = { workspace = true }
nix = { features = ["signal"], workspace = true }
node-cli = { workspace = true }
node-primitives = { workspace = true, default-features = true }
regex = { workspace = true }
sc-cli = { workspace = true, default-features = true }
sc-service = { workspace = true, default-features = true }
sp-rpc = { workspace = true, default-features = true }
substrate-rpc-client = { workspace = true, default-features = true }
tokio = { features = ["full"], workspace = true, default-features = true }

[features]
try-runtime = ["node-cli/try-runtime"]

