[package]
name = "coretime-rococo-emulated-chain"
version = "0.1.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Coretime Rococo emulated chain"
publish = false

[lints]
workspace = true

[dependencies]

# Substrate
frame-support = { workspace = true }
sp-core = { workspace = true }

# Cumulus
coretime-rococo-runtime = { workspace = true, default-features = true }
cumulus-primitives-core = { workspace = true }
emulated-integration-tests-common = { workspace = true }
parachains-common = { workspace = true, default-features = true }
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }

