[package]
name = "rococo-system-emulated-network"
version = "0.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Rococo System emulated network"
publish = false

[lints]
workspace = true

[dependencies]
# Cumulus
asset-hub-rococo-emulated-chain = { workspace = true }
bridge-hub-rococo-emulated-chain = { workspace = true }
coretime-rococo-emulated-chain = { workspace = true }
emulated-integration-tests-common = { workspace = true }
penpal-emulated-chain = { workspace = true }
people-rococo-emulated-chain = { workspace = true }
rococo-emulated-chain = { workspace = true }

