[package]
name = "pallet-minimal-template"
description = "A minimal pallet built with FRAME, part of Polkadot Sdk."
version = "0.0.0"
license = "Unlicense"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
edition = "2021"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
polkadot-sdk = { workspace = true, default-features = false, features = [
	"experimental",
	"runtime",
] }
scale-info = { features = ["derive"], workspace = true }


[features]
default = ["std"]
std = ["codec/std", "polkadot-sdk/std", "scale-info/std"]

