[package]
name = "xcm-procedural"
description = "Procedural macros for XCM"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
version = "7.0.0"
publish = true
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
Inflector = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
trybuild = { features = ["diff"], workspace = true }
# NOTE: we have to explicitly specify `std` because of trybuild
# https://github.com/paritytech/polkadot-sdk/pull/5167
xcm = { workspace = true, default-features = true, features = ["std"] }
# For testing macros.
frame-support = { workspace = true }

