[package]
name = "subkey"
version = "9.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
description = "Generate and restore keys for Substrate based chains such as Polkadot, Kusama and a growing number of parachains and Substrate based projects."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
path = "src/main.rs"
name = "subkey"

[dependencies]
clap = { features = ["derive"], workspace = true }
sc-cli = { workspace = true, default-features = true }

