[package]
name = "sc-telemetry"
version = "15.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
description = "Telemetry utils"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
documentation = "https://docs.rs/sc-telemetry"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
chrono = { workspace = true }
futures = { workspace = true }
libp2p = { features = ["dns", "tcp", "tokio", "websocket"], workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
pin-project = { workspace = true }
rand = { workspace = true, default-features = true }
sc-utils = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }
wasm-timer = { workspace = true }

