[package]
name = "pallet-nomination-pools-runtime-api"
version = "23.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Runtime API for nomination-pools FRAME pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
pallet-nomination-pools = { workspace = true }
sp-api = { workspace = true }

[features]
default = ["std"]
std = ["codec/std", "pallet-nomination-pools/std", "sp-api/std"]

