[package]
name = "polkadot-primitives-test-helpers"
publish = false
version = "1.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true

[lints]
workspace = true

[dependencies]
polkadot-primitives = { features = ["test"], workspace = true, default-features = true }
rand = { workspace = true, default-features = true }
sp-application-crypto = { workspace = true }
sp-core = { features = ["std"], workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

