[package]
name = "sp-core-hashing-proc-macro"
version = "15.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Procedural macros for calculating static hashes (deprecated in favor of `sp-crypto-hashing-proc-macro`)."
documentation = "https://docs.rs/sp-crypto-hashing-proc-macro"

[badges]
maintenance = { status = "deprecated" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-crypto-hashing-proc-macro = { workspace = true, default-features = true }

