[package]
name = "pallet-skip-feeless-payment"
version = "3.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Pallet to skip payments for calls annotated with `feeless_if` if the respective conditions are satisfied."

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate dependencies
sp-runtime = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }

# Other dependencies
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-runtime/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]

