[package]
name = "sc-utils"
version = "14.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "I/O for Substrate runtimes"
readme = "README.md"

[lints]
workspace = true

[dependencies]
async-channel = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
prometheus = { workspace = true }
sp-arithmetic = { workspace = true }

[features]
default = ["metered"]
metered = []

[dev-dependencies]
tokio-test = { workspace = true }

