[package]
name = "substrate-frame-rpc-support"
version = "29.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Substrate RPC for FRAME's support"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
frame-support = { workspace = true, default-features = true }
jsonrpsee = { features = ["jsonrpsee-types"], workspace = true }
sc-rpc-api = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
sp-storage = { workspace = true, default-features = true }

[dev-dependencies]
frame-system = { workspace = true, default-features = true }
jsonrpsee = { features = ["jsonrpsee-types", "ws-client"], workspace = true }
scale-info = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
tokio = { workspace = true, default-features = true }

