[package]
name = "polkadot-voter-bags"
version = "7.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
description = "CLI to generate voter bags for Polkadot runtimes"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[dependencies]
clap = { features = ["derive"], workspace = true }

generate-bags = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }

westend-runtime = { workspace = true }

