[package]
name = "polkadot-node-core-approval-voting-parallel"
version = "7.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
description = "Approval Voting Subsystem running approval work in parallel"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
gum = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }

polkadot-approval-distribution = { workspace = true, default-features = true }
polkadot-node-core-approval-voting = { workspace = true, default-features = true }
polkadot-node-metrics = { workspace = true, default-features = true }
polkadot-node-network-protocol = { workspace = true, default-features = true }
polkadot-node-primitives = { workspace = true, default-features = true }
polkadot-node-subsystem = { workspace = true, default-features = true }
polkadot-node-subsystem-util = { workspace = true, default-features = true }
polkadot-overseer = { workspace = true, default-features = true }
polkadot-primitives = { workspace = true, default-features = true }

sc-keystore = { workspace = true, default-features = false }
sp-application-crypto = { workspace = true, default-features = false, features = ["full_crypto"] }
sp-consensus = { workspace = true, default-features = false }
sp-consensus-slots = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }

rand = { workspace = true }
rand_chacha = { workspace = true }
rand_core = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
kvdb-memorydb = { workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true }
polkadot-node-subsystem-test-helpers = { workspace = true, default-features = true }
polkadot-primitives-test-helpers = { workspace = true, default-features = true }
polkadot-subsystem-bench = { workspace = true, default-features = true }
schnorrkel = { workspace = true, default-features = true }
sp-consensus-babe = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-keystore = { workspace = true, default-features = true }
sp-tracing = { workspace = true }

