[package]
name = "sp-consensus-slots"
version = "0.32.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
description = "Primitives for slots-based consensus"
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive", "max-encoded-len"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
serde = { features = ["alloc", "derive"], optional = true, workspace = true }
sp-timestamp = { workspace = true }

[features]
default = ["std"]
std = ["codec/std", "scale-info/std", "serde/std", "sp-timestamp/std"]

# Serde support without relying on std features.
serde = ["dep:serde", "scale-info/serde"]

