[package]
name = "node-primitives"
version = "2.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
description = "Substrate node low-level primitives."
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = ["sp-core/std", "sp-runtime/std"]

