[package]
name = "sp-inherents"
version = "26.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Provides types and traits for creating and checking inherents."
documentation = "https://docs.rs/sp-inherents"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { optional = true, workspace = true }
codec = { features = ["derive"], workspace = true }
impl-trait-for-tuples = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
sp-runtime = { optional = true, workspace = true }
thiserror = { optional = true, workspace = true }

[dev-dependencies]
futures = { workspace = true }

[features]
default = ["std"]
std = [
	"async-trait",
	"codec/std",
	"scale-info/std",
	"sp-runtime/std",
	"thiserror",
]

