[package]
name = "polkadot-node-core-chain-api"
version = "7.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
description = "The Chain API subsystem provides access to chain related utility functions like block number to hash conversions."
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gum = { workspace = true, default-features = true }
polkadot-node-metrics = { workspace = true, default-features = true }
polkadot-node-subsystem = { workspace = true, default-features = true }
polkadot-node-subsystem-types = { workspace = true, default-features = true }
sc-client-api = { workspace = true, default-features = true }
sc-consensus-babe = { workspace = true, default-features = true }

[dev-dependencies]
codec = { workspace = true, default-features = true }
futures = { features = ["thread-pool"], workspace = true }
maplit = { workspace = true }
polkadot-node-primitives = { workspace = true, default-features = true }
polkadot-node-subsystem-test-helpers = { workspace = true }
polkadot-primitives = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }

