[package]
name = "people-rococo-emulated-chain"
version = "0.1.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "People Rococo emulated chain"
publish = false

[dependencies]

# Substrate
frame-support = { workspace = true }
sp-core = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }
emulated-integration-tests-common = { workspace = true }
parachains-common = { workspace = true, default-features = true }
people-rococo-runtime = { workspace = true }
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }

