[package]
name = "generate-bags"
version = "28.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Bag threshold generation script for pallet-bag-list"

[lints]
workspace = true

[dependencies]
# FRAME
frame-election-provider-support = { workspace = true, default-features = true }
frame-support = { workspace = true, default-features = true }
frame-system = { workspace = true, default-features = true }
pallet-staking = { workspace = true, default-features = true }
sp-staking = { workspace = true, default-features = true }

# third party
chrono = { workspace = true }
num-format = { workspace = true }

