[package]
name = "bridge-hub-rococo-emulated-chain"
version = "0.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Bridge Hub Rococo emulated chain"
publish = false

[lints]
workspace = true

[dependencies]

# Substrate
frame-support = { workspace = true }
sp-core = { workspace = true }
sp-keyring = { workspace = true }

# Polkadot Dependencies
xcm = { workspace = true }

# Bridge dependencies
bp-messages = { workspace = true }

# Cumulus
bridge-hub-common = { workspace = true }
bridge-hub-rococo-runtime = { workspace = true, default-features = true }
emulated-integration-tests-common = { workspace = true }
parachains-common = { workspace = true, default-features = true }
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }

