[package]
name = "sc-storage-monitor"
version = "0.16.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Storage monitor service for substrate"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[dependencies]
clap = { features = ["derive", "string"], workspace = true }
fs4 = { workspace = true }
log = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
thiserror = { workspace = true }
tokio = { features = ["time"], workspace = true, default-features = true }

