[package]
name = "minimal-template-runtime"
description = "A solochain runtime template built with Substrate, part of Polkadot Sdk."
version = "0.0.0"
license = "Unlicense"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
edition = "2021"
publish = false

[dependencies]
codec = { workspace = true }
polkadot-sdk = { workspace = true, features = [
	"pallet-balances",
	"pallet-sudo",
	"pallet-timestamp",
	"pallet-transaction-payment",
	"pallet-transaction-payment-rpc-runtime-api",
	"runtime",
] }
scale-info = { workspace = true }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }

# local pallet templates
pallet-minimal-template = { workspace = true }

[build-dependencies]
polkadot-sdk = { optional = true, workspace = true, features = [
	"substrate-wasm-builder",
] }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-minimal-template/std",
	"polkadot-sdk/std",
	"scale-info/std",
	"serde_json/std",
]

