[package]
name = "sp-version-proc-macro"
version = "13.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Macro for defining a runtime version."
documentation = "https://docs.rs/sp-api-proc-macro"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
codec = { features = ["derive"], workspace = true, default-features = true }
proc-macro-warning = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { features = ["extra-traits", "fold", "full", "visit"], workspace = true }

[dev-dependencies]
sp-version = { workspace = true, default-features = true }

