[package]
name = "remote-ext-tests-bags-list"
publish = false
version = "1.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true

[lints]
workspace = true

[dependencies]
westend-runtime = { workspace = true }
westend-runtime-constants = { workspace = true, default-features = true }

frame-system = { workspace = true, default-features = true }
pallet-bags-list-remote-tests = { workspace = true }
sp-core = { workspace = true, default-features = true }
sp-tracing = { workspace = true, default-features = true }

clap = { features = ["derive"], workspace = true }
log = { workspace = true, default-features = true }
tokio = { features = ["macros"], workspace = true, default-features = true }

