[package]
name = "sp-timestamp"
version = "26.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Substrate core types and inherents for timestamps."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { optional = true, workspace = true }
codec = { features = ["derive"], workspace = true }
sp-inherents = { workspace = true }
sp-runtime = { workspace = true }
thiserror = { optional = true, workspace = true }

[features]
default = ["std"]
std = [
	"async-trait",
	"codec/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"thiserror",
]

