[package]
name = "pallet-bags-list-fuzzer"
version = "4.0.0-dev"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Fuzzer for FRAME pallet bags list"
publish = false

[lints]
workspace = true

[dependencies]
frame-election-provider-support = { features = ["fuzz"], workspace = true, default-features = true }
honggfuzz = { workspace = true }
pallet-bags-list = { features = ["fuzz"], workspace = true, default-features = true }
rand = { features = ["small_rng", "std"], workspace = true, default-features = true }

[[bin]]
name = "bags-list"
path = "src/main.rs"

