[package]
name = "cumulus-pov-validator"
version = "0.1.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
license.workspace = true
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "A tool for validating PoVs locally"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
codec.workspace = true
polkadot-node-primitives.workspace = true
polkadot-parachain-primitives.workspace = true
polkadot-primitives.workspace = true
sc-executor.workspace = true
sp-core.workspace = true
sp-io.workspace = true
sp-maybe-compressed-blob.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[lints]
workspace = true

