[package]
name = "polkadot-runtime-metrics"
version = "7.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
description = "Runtime metric interface for the Polkadot node"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
frame-benchmarking = { optional = true, workspace = true }
polkadot-primitives = { workspace = true }
sp-tracing = { workspace = true }

bs58 = { features = ["alloc"], workspace = true }

[features]
default = ["std"]
std = [
	"bs58/std",
	"codec/std",
	"frame-benchmarking?/std",
	"polkadot-primitives/std",
	"sp-tracing/std",
]
runtime-metrics = ["frame-benchmarking", "sp-tracing/with-tracing"]

