[package]
name = "sp-arithmetic"
version = "23.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Minimal fixed point arithmetic primitives and types for runtime."
documentation = "https://docs.rs/sp-arithmetic"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
	"max-encoded-len",
], workspace = true }
docify = { workspace = true }
integer-sqrt = { workspace = true }
num-traits = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
serde = { features = ["alloc", "derive"], optional = true, workspace = true }
static_assertions = { workspace = true, default-features = true }

[dev-dependencies]
criterion = { workspace = true, default-features = true }
primitive-types = { workspace = true, default-features = true }
rand = { workspace = true, default-features = true }
sp-crypto-hashing = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"num-traits/std",
	"scale-info/std",
	"serde/std",
	"sp-crypto-hashing/std",
]
# Serde support without relying on std features.
serde = ["dep:serde", "scale-info/serde"]

[[bench]]
name = "bench"
harness = false

