[package]
name = "penpal-emulated-chain"
version = "0.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Penpal emulated chain"
publish = false

[lints]
workspace = true

[dependencies]

# Substrate
frame-support = { workspace = true }
sp-core = { workspace = true }
sp-keyring = { workspace = true }

# Polkadot
xcm = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }
emulated-integration-tests-common = { workspace = true }
parachains-common = { workspace = true, default-features = true }
penpal-runtime = { workspace = true }

