[package]
name = "polkadot-node-core-prospective-parachains"
version = "6.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
description = "The Prospective Parachains subsystem. Tracks and handles prospective parachain fragments."
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[dependencies]
fatality = { workspace = true }
futures = { workspace = true }
gum = { workspace = true, default-features = true }
thiserror = { workspace = true }

polkadot-node-subsystem = { workspace = true, default-features = true }
polkadot-node-subsystem-util = { workspace = true, default-features = true }
polkadot-primitives = { workspace = true, default-features = true }

[dev-dependencies]
assert_matches = { workspace = true }
polkadot-node-subsystem-test-helpers = { workspace = true }
polkadot-primitives = { workspace = true, features = ["test"] }
polkadot-primitives-test-helpers = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
sp-core = { workspace = true, default-features = true }
sp-tracing = { workspace = true }

