[package]
name = "staging-node-inspect"
version = "0.12.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
description = "Substrate node block inspection tool."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { features = ["derive"], workspace = true }
codec = { workspace = true, default-features = true }
sc-cli = { workspace = true }
sc-client-api = { workspace = true, default-features = true }
sc-service = { workspace = true }
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-statement-store = { workspace = true, default-features = true }
thiserror = { workspace = true }

[features]
runtime-benchmarks = [
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]

