[package]
name = "pallet-paged-list-fuzzer"
version = "0.1.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"
description = "Fuzz storage types of pallet-paged-list"
publish = false

[lints]
workspace = true

[[bin]]
name = "pallet-paged-list-fuzzer"
path = "src/paged_list.rs"

[dependencies]
arbitrary = { workspace = true }
frame = { workspace = true, features = ["runtime"] }
honggfuzz = { workspace = true }
pallet-paged-list = { features = ["std"], workspace = true }

[features]
default = ["std"]
std = [
	"frame/std",
	"pallet-paged-list/std",
]

