[package]
name = "slot-range-helper"
version = "7.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true
description = "Helper crate for generating slot ranges for the Polkadot runtime."
homepage = "https://github.com/Skhi-Bridges/polkadot-sdk"
repository = "https://github.com/Skhi-Bridges/polkadot-sdk"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
enumn = { workspace = true }
paste = { workspace = true, default-features = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = ["codec/std", "sp-runtime/std"]

