[package]
name = "test-runtime-constants"
publish = false
version = "1.0.0"
authors = ["Matrix-Magiq Team", "Parity Technologies <admin@parity.io>"]
edition = "2021"
license.workspace = true

[lints]
workspace = true

[dependencies]
smallvec = { workspace = true, default-features = true }

frame-support = { workspace = true }
polkadot-primitives = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"polkadot-primitives/std",
	"sp-runtime/std",
]

